/* Central game catalog. Every game on the site lives here.
   cats: category ids from GAME_CATEGORIES. external: opens the raw URL instead of the player page. */

window.GAME_CATEGORIES = [
	{ id: "popular", name: "Popular", icon: "flame" },
	{ id: "action", name: "Action", icon: "zap" },
	{ id: "arcade", name: "Arcade", icon: "gamepad" },
	{ id: "puzzle", name: "Puzzle", icon: "puzzle" },
	{ id: "racing", name: "Racing", icon: "car" },
	{ id: "sports", name: "Sports", icon: "ball" },
	{ id: "running", name: "Running", icon: "speed" },
	{ id: "platformer", name: "Platformer", icon: "mushroom" },
	{ id: "clicker", name: "Clicker & Idle", icon: "mouse" },
	{ id: "io", name: ".io Games", icon: "globe" },
	{ id: "two-player", name: "2 Player", icon: "users" },
	{ id: "cooking", name: "Cooking", icon: "pan" },
	{ id: "casual", name: "Casual", icon: "balloon" },
	{ id: "horror", name: "Horror", icon: "ghost" },
	{ id: "strategy", name: "Strategy", icon: "pawn" },
	{ id: "classic", name: "Classic", icon: "hourglass" },
	{ id: "mini", name: "Mini Games", icon: "flask" }
];

/* Inline SVG icon set (stroke-based, inherits currentColor). */
window.SITE_ICONS = {
	home: '<path d="M3 10.5 12 3l9 7.5"/><path d="M5 10v10h14V10"/>',
	dice: '<rect x="4" y="4" width="16" height="16" rx="3"/><circle cx="9" cy="9" r="1.2" fill="currentColor" stroke="none"/><circle cx="15" cy="9" r="1.2" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.2" fill="currentColor" stroke="none"/><circle cx="9" cy="15" r="1.2" fill="currentColor" stroke="none"/><circle cx="15" cy="15" r="1.2" fill="currentColor" stroke="none"/>',
	star: '<path d="M12 3l2.7 5.8 6.3.8-4.6 4.4 1.2 6.2L12 17.3 6.4 20.2l1.2-6.2L3 9.6l6.3-.8z"/>',
	clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/>',
	info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5"/><circle cx="12" cy="8" r="1.1" fill="currentColor" stroke="none"/>',
	search: '<circle cx="11" cy="11" r="7"/><path d="M16.5 16.5L21 21"/>',
	menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
	back: '<path d="M19 12H5"/><path d="M11 18l-6-6 6-6"/>',
	fullscreen: '<path d="M4 9V4h5"/><path d="M15 4h5v5"/><path d="M20 15v5h-5"/><path d="M9 20H4v-5"/>',
	flame: '<path d="M12 3c1 3-4 5-4 9a4 4 0 0 0 8 0c0-2-1-3.5-2-5-.5 1.5-1 2-2 2.5C12.5 7.5 13 5 12 3z"/>',
	zap: '<path d="M13 2L4 14h6l-1 8 9-12h-6l1-8z"/>',
	gamepad: '<rect x="3" y="8" width="18" height="9" rx="4.5"/><path d="M8 10.5v4M6 12.5h4"/><circle cx="15.5" cy="11.5" r="1" fill="currentColor" stroke="none"/><circle cx="17.5" cy="13.5" r="1" fill="currentColor" stroke="none"/>',
	puzzle: '<path d="M14 3v2a2 2 0 1 0 4 0V3h3v7h-2a2 2 0 1 0 0 4h2v7h-7v-2a2 2 0 1 0-4 0v2H3v-7h2a2 2 0 1 0 0-4H3V3z"/>',
	car: '<path d="M5 11l1.5-4.5A2 2 0 0 1 8.4 5h7.2a2 2 0 0 1 1.9 1.5L19 11"/><rect x="3" y="11" width="18" height="6" rx="2"/><circle cx="7.5" cy="19.5" r="1.5"/><circle cx="16.5" cy="19.5" r="1.5"/>',
	ball: '<circle cx="12" cy="12" r="9"/><path d="M12 8l3.2 2.3-1.2 3.7h-4l-1.2-3.7z"/><path d="M12 8V3.5M15.2 10.3l4.3-1.4M14 14l2.6 3.6M10 14l-2.6 3.6M8.8 10.3L4.5 8.9"/>',
	speed: '<path d="M5 6l6 6-6 6"/><path d="M13 6l6 6-6 6"/>',
	mushroom: '<path d="M4 12a8 8 0 0 1 16 0z"/><path d="M9 12v5a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-5"/><circle cx="12" cy="8" r="1" fill="currentColor" stroke="none"/><circle cx="8" cy="10" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="10" r="1" fill="currentColor" stroke="none"/>',
	mouse: '<rect x="7" y="3" width="10" height="18" rx="5"/><path d="M12 7v3"/>',
	globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><ellipse cx="12" cy="12" rx="4.5" ry="9"/>',
	users: '<circle cx="9" cy="8" r="3.5"/><path d="M3 20c0-3.3 2.7-6 6-6s6 2.7 6 6"/><circle cx="17" cy="9" r="2.8"/><path d="M17.5 14.2c2.6.6 4.5 2.9 4.5 5.8"/>',
	pan: '<circle cx="10" cy="12" r="6"/><circle cx="10" cy="12" r="2" fill="currentColor" stroke="none"/><path d="M16 12h6"/>',
	balloon: '<ellipse cx="12" cy="9" rx="6" ry="7"/><path d="M11 16.5h2l-1 1.8z"/><path d="M12 18.5c0 2-2 1.5-2 3.5"/>',
	ghost: '<path d="M5 11a7 7 0 0 1 14 0v9l-2.3-2-2.35 2-2.35-2-2.35 2L9.3 18 5 20z"/><circle cx="9.5" cy="11" r="1.1" fill="currentColor" stroke="none"/><circle cx="14.5" cy="11" r="1.1" fill="currentColor" stroke="none"/>',
	pawn: '<circle cx="12" cy="7" r="3"/><path d="M10.5 9.5L8 17h8l-2.5-7.5"/><path d="M6 20h12"/>',
	hourglass: '<path d="M7 3h10v4l-4 4v2l4 4v4H7v-4l4-4v-2L7 7z"/>',
	flask: '<path d="M10 3v6l-5.5 9a2 2 0 0 0 1.7 3h11.6a2 2 0 0 0 1.7-3L14 9V3"/><path d="M8.5 3h7"/><path d="M7 15h10"/>'
};

window.iconSVG = function (name, cls) {
	var body = window.SITE_ICONS[name];
	if (!body) return "";
	return '<svg class="icon' + (cls ? " " + cls : "") + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + body + "</svg>";
};

window.GAMES = [
	{ id: "2048", name: "2048", href: "2048/index.html", img: "images/2048.jpg", cats: ["puzzle", "popular", "classic"] },
	{ id: "wordle", name: "Wordle", href: "wordle/index.html", img: "images/wordle.jpg", cats: ["puzzle", "popular"] },
	{ id: "dogeminer", name: "DogeMiner", href: "DogeMiner/index.html", img: "images/dog.jpg", cats: ["clicker"] },
	{ id: "slope", name: "Slope", href: "slope/index.html", img: "images/slope.jpeg", cats: ["running", "popular"] },
	{ id: "survev", name: "Survev.io", href: "survevio.html", img: "images/survev.png", cats: ["io", "action", "popular"] },
	{ id: "bitlife", name: "BitLife", href: "bitlife/index.html", img: "bitlife/logo.png", cats: ["casual", "popular"] },
	{ id: "snake", name: "Snake", href: "snake/index.html", img: "images/snake.jpg", cats: ["arcade", "classic"] },
	{ id: "retro-bowl", name: "Retro Bowl", href: "retro-bowl/index.html", img: "images/retro.jpg", cats: ["sports", "popular"] },
	{ id: "cell-machine", name: "Cell Machine", href: "cell/index.html", img: "images/cell.jpg", cats: ["puzzle"] },
	{ id: "cookie-clicker", name: "Cookie Clicker", href: "cookieclicker/index.html", img: "images/cookie.jpg", cats: ["clicker", "popular"] },
	{ id: "subway-surfers", name: "Subway Surfers", href: "Subway2/index.html", img: "images/subway.jpg", cats: ["running", "popular"] },
	{ id: "touch", name: "Touch", href: "touch/index.html", img: "images/touch.jpg", cats: ["arcade"] },
	{ id: "tunnel-rush", name: "Tunnel Rush", href: "tunnelrush/index.html", img: "images/tunnel.jpg", cats: ["running"] },
	{ id: "tetris", name: "Tetris", href: "tetris/index.html", img: "images/tetris.jpg", cats: ["puzzle", "classic"] },
	{ id: "happy-wheels", name: "Happy Wheels", href: "happy/index.html", img: "images/happy.jpg", cats: ["action", "popular"] },
	{ id: "robogo", name: "RoboGo", href: "robogo/index.html", img: "images/robogo.jpg", cats: ["platformer"] },
	{ id: "soccer-random", name: "Soccer Random", href: "soccer-random/index.html", img: "images/soccer.jpg", cats: ["sports", "two-player"] },
	{ id: "geometry-dash", name: "Geometry Dash", href: "https://scratch.mit.edu/projects/105500895", img: "images/Geometry.jpg", cats: ["platformer", "popular"], external: true },
	{ id: "portaboy", name: "PortaBoy", href: "portaboy/index.html", img: "images/porta.jpg", cats: ["arcade"] },
	{ id: "sword", name: "Sword", href: "sword/index.html", img: "images/sword.jpg", cats: ["action"] },
	{ id: "fruit-ninja", name: "Fruit Ninja", href: "fruitninja/index.html", img: "images/fruitninja.jpg", cats: ["arcade"] },
	{ id: "knife-hit", name: "Knife Hit", href: "knifehit/index.html", img: "images/knife.jpg", cats: ["arcade"] },
	{ id: "crossy-road", name: "Crossy Road", href: "crossy/index.html", img: "images/crossy.jpg", cats: ["arcade", "popular"] },
	{ id: "jetpack-joyride", name: "Jetpack Joyride", href: "jetpackjoyride/index.html", img: "images/jetpack.jpg", cats: ["running", "action"] },
	{ id: "breaklock", name: "BreakLock", href: "breaklock/index.html", img: "images/lock.jpg", cats: ["puzzle"] },
	{ id: "bison", name: "Bison", href: "bison/index.html", img: "images/bison.jpg", cats: ["action"] },
	{ id: "doodle-jump", name: "Doodle Jump", href: "doodle/index.html", img: "images/doodle.jpg", cats: ["platformer", "arcade", "classic"] },
	{ id: "adventure-capitalist", name: "AdVenture Capitalist", href: "adcap/index.html", img: "images/adcap.jpg", cats: ["clicker"] },
	{ id: "assessment", name: "Assessment", href: "assessment/index.html", img: "images/assessment.jpg", cats: ["casual"] },
	{ id: "baldis-basics", name: "Baldi's Basics", href: "baldi/index.html", img: "images/baldi.jpg", cats: ["horror", "popular"] },
	{ id: "basketball-legends", name: "Basketball Legends", href: "basketball-legends/index.html", img: "images/basketballL.jpg", cats: ["sports", "two-player"] },
	{ id: "basketball-stars", name: "Basketball Stars", href: "basketball-stars/index.html", img: "images/basketballS.jpg", cats: ["sports", "two-player"] },
	{ id: "boxing-physics-2", name: "Boxing Physics 2", href: "boxing-physics2/index.html", img: "images/boxing2.jpg", cats: ["sports", "two-player"] },
	{ id: "burger", name: "Burger", href: "burger/index.html", img: "images/burger.jpg", cats: ["cooking", "casual"] },
	{ id: "chrome-dino", name: "Chrome Dino", href: "chrome-dino/index.html", img: "images/chromedino.jpg", cats: ["running", "classic"] },
	{ id: "doodle-god", name: "Doodle God", href: "doodlegod/index.html", img: "images/doodlegod.jpg", cats: ["puzzle", "casual"] },
	{ id: "dreader", name: "Dreader", href: "dreader/index.html", img: "images/dreader.jpg", cats: ["horror"] },
	{ id: "drift", name: "Drift", href: "drift/index.html", img: "images/drift.jpg", cats: ["racing"] },
	{ id: "exhibit", name: "Exhibit", href: "exhibit/index.html", img: "images/ex2.jpg", cats: ["horror"] },
	{ id: "papas-freezeria", name: "Papa's Freezeria", href: "freezeria/index.html", img: "images/freezeria.jpg", cats: ["cooking", "popular"] },
	{ id: "friendly-fire", name: "Friendly Fire", href: "friendlyfire/index.html", img: "images/fire.jpg", cats: ["action", "two-player"] },
	{ id: "greybox", name: "Greybox", href: "greybox/index.html", img: "images/greybox.jpg", cats: ["puzzle"] },
	{ id: "slither-io", name: "Slither.io", href: "slither.io-clone-master/slither-container.html", img: "images/slither.jpg", cats: ["io", "popular", "classic"] },
	{ id: "mario-run", name: "Mario Run", href: "Mario.Run-master/index.html", img: "images/mario2.jpg", cats: ["platformer", "running"] },
	{ id: "hill-climb", name: "Hill Climb", href: "Hill-master/index.html", img: "images/brand.jpg", cats: ["racing"] },
	{ id: "suika-game", name: "Suika Game", href: "suika-game-main-2/index.html", img: "images/suika.webp", cats: ["puzzle", "popular"] },
	{ id: "infinite-cars", name: "Infinite Cars", href: "infinite-cars-main/index.html", img: "images/infinity.jpg", cats: ["racing"] },
	{ id: "super-mario-bros", name: "Super Mario Bros", href: "Super-Mario-Bros-master/index.html", img: "images/mario.jpg", cats: ["platformer", "classic", "popular"] },
	{ id: "road", name: "Road", href: "Road-master/index.html", img: "images/road.jpg", cats: ["racing"] },
	{ id: "cut-the-rope", name: "Cut the Rope", href: "CutTheRope-master/index.html", img: "images/cut.jpg", cats: ["puzzle"] },
	{ id: "highway-traffic", name: "Highway Traffic", href: "highway/index.html", img: "images/highway.jpg", cats: ["racing"] },
	{ id: "snow-rider", name: "Snow Rider", href: "Snow-Rider/index.html", img: "images/snow.jpg", cats: ["racing", "popular"] },
	{ id: "territorial-io", name: "Territorial.io", href: "teritorial/static/index.html", img: "images/territorial.jpg", cats: ["io", "strategy"] },
	{ id: "fireboy-watergirl", name: "Fireboy and Watergirl", href: "fireboy_watergirl/index.html", img: "images/firewater.jpg", cats: ["two-player", "platformer", "popular"] },
	{ id: "paper-io", name: "Paper.io", href: "paper.io/ifr.html", img: "images/paper.jpg", cats: ["io"] },
	{ id: "lose-95", name: "Lose 95", href: "lose95/index.html", img: "images/95.jpg", cats: ["casual"] },
	{ id: "getaway-shootout", name: "Getaway Shootout", href: "getaway-shootout/index.html", img: "images/shoot.jpg", cats: ["action", "two-player"] },
	{ id: "monkey-mart", name: "Monkey Mart", href: "monkey/index.html", img: "images/monkey.jpg", cats: ["casual", "popular"] },
	{ id: "stickman-hook", name: "Stickman Hook", href: "Stickmanhook/index.html", img: "images/stick.jpg", cats: ["arcade", "popular"] },
	{ id: "dogeminer-2", name: "DogeMiner 2", href: "Dogeminer2/index.html", img: "images/doge2.jpg", cats: ["clicker"] },
	{ id: "yohoho", name: "YoHoHo.io", href: "yohoho/index.html", img: "images/yohoho.jpg", cats: ["io", "action"] },
	{ id: "worlds-hardest-game-2", name: "World's Hardest Game 2", href: "worlds-hardest-game-2/index.html", img: "images/hard.jpg", cats: ["arcade", "puzzle"] },
	{ id: "missiles", name: "Missiles", href: "Missiles/index.html", img: "images/miss.jpg", cats: ["arcade"] },
	{ id: "drive-mad", name: "Drive Mad", href: "DriveMad/index.html", img: "images/drivemad.jpg", cats: ["racing", "popular"] },
	{ id: "aquapark-slides", name: "Aquapark Slides", href: "aquapark-slides/index.html", img: "images/aqaua.jpg", cats: ["casual"] },
	{ id: "ballistic-chickens", name: "Ballistic Chickens", href: "BallisticChickens/index.html", img: "images/chickens.jpg", cats: ["arcade"] },
	{ id: "subway-surfers-2", name: "Subway Surfers 2", href: "subway-surfers/index.html", img: "images/surfers.jpg", cats: ["running"] },
	{ id: "sticky-road", name: "Sticky Road", href: "sticky-road/index.html", img: "images/stickyroad.jpg", cats: ["racing"] },
	{ id: "blumgi-magic-ball", name: "Blumgi Magic Ball", href: "BlumgiMagicBall/index.html", img: "images/magicball.jpg", cats: ["arcade"] },
	{ id: "head-soccer-2022", name: "Head Soccer 2022", href: "HeadSoccer2022/index.html", img: "images/headsoccer.jpg", cats: ["sports", "two-player"] },
	{ id: "stick-duel", name: "Stick Duel", href: "stickduel/index.html", img: "images/stickduel.jpg", cats: ["action", "two-player"] },
	{ id: "fireboy-watergirl-2", name: "Fireboy and Watergirl 2", href: "Fireboy-and-Watergirl-main/index.html", img: "images/fireboywatergirl.jpg", cats: ["two-player", "platformer"] },

	/* Papa's series */
	{ id: "papas-pizzeria", name: "Papa's Pizzeria", href: "papas/papas_pizzeria.html", img: "images/p_pizzeria.jpg", cats: ["cooking"] },
	{ id: "papas-bakeria", name: "Papa's Bakeria", href: "papas/papas-bakeria.html", img: "images/p_bakeria.jpg", cats: ["cooking"] },
	{ id: "papas-burgeria", name: "Papa's Burgeria", href: "papas/papas-burgeria.html", img: "images/p_burgeria.jpg", cats: ["cooking"] },
	{ id: "papas-cheeseria", name: "Papa's Cheeseria", href: "papas/papas-cheeseria.html", img: "images/p_cheeseria.jpg", cats: ["cooking"] },
	{ id: "papas-cupcakeria", name: "Papa's Cupcakeria", href: "papas/papas-cupcakeria.html", img: "images/p_cupcakeria.jpg", cats: ["cooking"] },
	{ id: "papas-donuteria", name: "Papa's Donuteria", href: "papas/papas-donuteria.html", img: "images/p_donuteria.jpg", cats: ["cooking"] },
	{ id: "papas-hot-doggeria", name: "Papa's Hot Doggeria", href: "papas/papas-hot-doggeria.html", img: "images/p_hot.jpg", cats: ["cooking"] },
	{ id: "papas-pastaria", name: "Papa's Pastaria", href: "papas/papas-pastaria.html", img: "images/p_pastaria.jpg", cats: ["cooking"] },
	{ id: "papas-sushiria", name: "Papa's Sushiria", href: "papas/papas-sushiria.html", img: "images/p_shushiria.jpg", cats: ["cooking"] },
	{ id: "papas-taco-mia", name: "Papa's Taco Mia", href: "papas/papas-taco-mia.html", img: "images/p_taco.jpg", cats: ["cooking"] },
	{ id: "papas-wingeria", name: "Papa's Wingeria", href: "papas/papas-wingeria.html", img: "images/p_wingeria.jpg", cats: ["cooking"] },

	/* Small single-file & mini games */
	{ id: "maze", name: "Maze", href: "maze.html", img: "images/agar.jpg", cats: ["puzzle", "mini"] },
	{ id: "mario", name: "Mario", href: "mario/index.html", img: "images/mario3.jpg", cats: ["platformer", "mini"] },
	{ id: "pokemon", name: "Pokemon", href: "pokemon/index.html", img: "images/pokemon.jpg", cats: ["casual", "classic", "mini"] },
	{ id: "brick-breaker", name: "Brick Breaker", href: "brick-breaker.html", img: "images/agar.jpg", cats: ["arcade", "mini"] },
	{ id: "connect-the-pipes", name: "Connect the Pipes", href: "Connect the Pipes.html", img: "images/mario3.jpg", cats: ["puzzle", "mini"] },
	{ id: "tower-defence", name: "Tower Defence", href: "HTML Tower Defence.html", img: "images/pokemon.jpg", cats: ["strategy", "mini"] },
	{ id: "mini-car-game", name: "Mini Car Game", href: "mini_car_game.html", img: "images/agar.jpg", cats: ["racing", "mini"] },
	{ id: "tic-tac-toe", name: "Tic Tac Toe", href: "tic-tac-toe.html", img: "images/mario3.jpg", cats: ["puzzle", "two-player", "mini"] },
	{ id: "snake-game", name: "Snake Game", href: "Snakegame.html", img: "images/pokemon.jpg", cats: ["arcade", "mini"] },
	{ id: "audio-game", name: "Audio Game", href: "audio-game/index.htm", img: "images/surfers.jpg", cats: ["casual", "mini"] },
	{ id: "ball-shooting", name: "Ball Shooting", href: "ball-shooting/index.html", img: "images/stickyroad.jpg", cats: ["arcade", "mini"] },
	{ id: "box2d-car-game", name: "Box2D Car Game", href: "box2d-car-game/index.htm", img: "images/magicball.jpg", cats: ["racing", "mini"] },
	{ id: "untangle", name: "Untangle", href: "canvas-untangle-game/index.html", img: "images/surfers.jpg", cats: ["puzzle", "mini"] },
	{ id: "count-99", name: "Count 99", href: "count-99/index.html", img: "images/stickyroad.jpg", cats: ["casual", "mini"] },
	{ id: "matching-game", name: "Matching Game", href: "css3-matching-game/index.html", img: "images/magicball.jpg", cats: ["puzzle", "mini"] },
	{ id: "multiply-defense", name: "Multiply Defense", href: "multiply-defense/index.html", img: "images/surfers.jpg", cats: ["strategy", "mini"] },
	{ id: "ping-pong", name: "Ping Pong", href: "pingpoing/index.html", img: "images/stickyroad.jpg", cats: ["arcade", "sports", "mini"] },
	{ id: "rush", name: "Rush", href: "rush/index.html", img: "images/magicball.jpg", cats: ["arcade", "mini"] }
];
